GET  https://my-office-mern-app.herokuapp.com/workers

# ###

# POST http://localhost:8000/workers/

# Content-Type: application/json 

# {
#     "firstName":"BazazaoB",
#     "lastName":"BazziB"
# }
###

POST https://my-office-mern-app.herokuapp.com/workers